backend:
  name: git-gateway
  branch: main

# Enable manual authentication settings  
site_url: https://businessnewslive.netlify.app
logo_url: https://businessnewslive.netlify.app/logo.png  

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
