backend:
  name: Jatin9692
  repo: newssight-hub 
  branch: main  # Change to 'master' if your repo uses 'master' branch

media_folder: "images/uploads" # Where uploaded images go
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
